### ISSUE TITLE
Why are errors and exceptions just pipelined into stdout, not even through a logging system?

### ISSUE THREAD

**Issue by ipg0** [ATran31/osrm-java-client#1]
For example, `services/route.java:41`:
```java
} catch (Exception e){
  System.out.println(e.getMessage());
}
```
Since this project is intended to be embedded in a larger system (I guess), you should probably catch that and throw an exception that clarifies why the request failed.

**Comment by ATran31** [comment]
This project was just part of a discovery exercise, for an idea that never fully materialized. I never completed it, and no longer maintain it.
